### PR TITLE
big refactor! moving altbn128 into native's repo & adding secp256k1 native library

### PR DESCRIPTION
**Pull request by fedejinich**
Big refactor

- Now this repo will provide all the native libraries used in rskj
- Adding secp256k1 library (from [bitcoin-core](https://github.com/bitcoin-core/secp256k1))

All these new features have been documented at README.md

### CODE REVIEW

**Comment by fedejinich** [comment]
just squashed some commits

**Review by patogallaiovlabs — DISMISSED** [review]

**Review by alejandrod-iov — DISMISSED** [review]
Cloned the the native repo, and performed the `sudo ./gradlew buildProject` and worked OK.

```BUILD SUCCESSFUL in 2m 24s
7 actionable tasks: 6 executed, 1 up-to-date```

**Review by alejandrod-iov — APPROVED** [review]
I waas able to build the jar file using readme instructions

**Review by alejandrod-iov — DISMISSED** [review]
I was able to build the jar file using readme instructions

**Comment by donequis** [comment]
Hi! Can we remove the privileges and docker requirement for linux?

I just removed docker from `./build-linux.sh` and `./tests.sh` (and added the `#!/bin/bash`) and it worked. And docker, for the reproducible build, should call gradle, not the other way around if possible.

And for the reproducible I just added the gradle call at the end of the dockerfile (this would build libraries twice, I'm pointing out that it just works).

So we should end with two options: a `./gradlew buildProject` for local building and a Dockerfile for the reproducible build.

**Comment by fedejinich** [comment]
sure @donequis ! on it

**Comment by fedejinich** [comment]
@donequis done!

as we agreed, there are two ways to build the project

- productive one (through docker)
- development by calling `./gradlew buildProject`

**Comment by fedejinich** [comment]
after talking with @donequis we've decided that this PR is ready to merge @aeidelman

**Review by aeidelman — APPROVED** [review]
According to what I talked with @donequis, we are ok with moving forward and merge this PR

**Pull request merged**
